### ISSUE TITLE
Improve the documentation before 1.0.0 is released

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#580] opened 2022-07-27 11:53 UTC
**Improve**
https://astro-sdk.readthedocs.io/en/1.0.0b1/

**Goal**
Improve the content itself.

**Acceptance criteria**
* [ ] Add section about supported technologies: https://github.com/astronomer/astro-sdk#supported-technologies
* [ ] API Reference and Changelog should be after the Getting Started section on the left menu
* [ ] Configuration section: a summary of all available parameters and configuration
* [ ] Things to hide in the API Reference
    - databases
    - utils
* [ ] Have a Concepts section where we explain:
   - File
   - Tables (temporary table)
   - Operators/Decorators & Task Flow API
   - Details about native `aql.load_file`
   - Append x merge
* [ ] Create section "Examples" - include the explanation of the example of dynamic task mapping

**Comment by utkarsharma2** [comment] 2022-08-18 17:55
Duplicate of documentation epic

**Closed by utkarsharma2** 2022-08-18 17:55 UTC
Labels: documentation, priority/critical
