### ISSUE TITLE
Postgres tables being created in default schema 

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#599] opened 2022-08-01 12:53 UTC
When a postgres connection is created with a particular schema , say "postgres", the table gets created in a schema called "tmp_astro" which ideally shouldnt be the case.

Schema name should be read from connection properties and the table should be created accordingly.

**Comment by kaxil** [comment] 2022-08-03 13:49
@tatiana mentioned that there is already a ticket for it. She will post it here

**Comment by kaxil** [comment] 2022-08-03 13:49
https://github.com/astronomer/astro-sdk/issues/304 this was it

**Comment by pankajkoti** [comment] 2022-08-04 06:34
@utkarsharma2 Please link the correct existing ticket

**Comment by sunank200** [comment] 2022-08-08 13:50
As @tatiana mentioned :
- In Postgres, databases and schema are different concepts: https://www.postgresql.org/docs/current/ddl-schemas.html
- the PostgresHook only exposes schema: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/_api/airflow/providers/postgres/hooks/postgres/index.html
However, implementation-wise, it seems that if the PostgresHook receives a schema during initialisation, but it uses it as a database in  the connection to Postgres: https://github.com/apache/airflow/blob/main/airflow/providers/postgres/hooks/postgres.py#L96


So for this change is required on OSS airflow in class `PostgresHook`

**Comment by phanikumv** [comment] 2022-08-08 14:43
AFAIK it should not use `tmp_astro`  schema, when user provides a schema in connection

**Comment by sunank200** [comment] 2022-08-08 14:47
That's correct but the way airflow hook handles schema is wrong right now. It treats the database as schema from connections as per https://github.com/apache/airflow/blob/main/airflow/providers/postgres/hooks/postgres.py#L96.

This would require change on the OSS airflow side which is a breaking change on the airflow side as well. Also, we shouldn’t use database and schema as the same value. The problem is: that Airflow Postgres Hook exposes the Postgres Database property incorrectly with the name schema. That’s why we’re doing this in the Astro SDK till its fixed on OSS airflow side

**Closed** 2022-08-09 10:02 UTC
Labels: priority/high
