### ISSUE TITLE
Fix Flaky Bigquery test: `test_bigquery_create_table_with_columns[bigquery]`

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#656] opened 2022-08-15 17:52 UTC
The test (`tests/databases/test_bigquery.py::test_bigquery_create_table_with_columns[bigquery]`) on main and some of the PRs are failing with the following error

```
FAILED tests/databases/test_bigquery.py::test_bigquery_create_table_with_columns[bigquery]

>       assert rows[0] == (
            "astronomer-dag-authoring",
            f"***table.metadata.schema***",
            f"***table.name***",
            "id",
            1,
            "NO",
            "INT64",
            "NEVER",
            None,
            None,
            "NO",
            None,
            "NO",
            "NO",
            None,
            "NULL",
        )
E       AssertionError: assert ('astronomer-...NULL', 'NULL') == ('astronomer-... 1, 'NO', ...)
E         Left contains one more item: 'NULL'
E         Full diff:
E           (
E         +  'astronomer-dag-authoring', 'astroflow_ci', '_tmp_pesruzahysightbwpar4ovdslf0p74d6i5ijzgvv1cpz3', 'id', 1, 'NO', 'INT64', 'NEVER', None, None, 'NO', None, 'NO', 'NO', None, 'NULL', 'NULL',
E         -  'astronomer-dag-authoring',
E         -  'astroflow_ci',
E         -  '_tmp_pesruzahysightbwpar4ovdslf0p74d6i5ijzgvv1cpz3',
E         -  'id',
E         -  1,
E         -  'NO',
E         -  'INT64',
E         -  'NEVER',
E         -  None,
E         -  None,
E         -  'NO',
E         -  None,
E         -  'NO',
E         -  'NO',
E         -  None,
E         -  'NULL',
E           )
```

Example failure: https://github.com/astronomer/astro-sdk/runs/7830499547?check_suite_focus=true

**Comment by utkarsharma2** [comment] 2022-08-16 09:25
Duplicate of - 660

**Closed by utkarsharma2** 2022-08-16 09:25 UTC
