### ISSUE TITLE
Use dbt-snowflake and astro-sdk-python on astro-cli

### ISSUE THREAD

**Issue by sunank200** [astronomer/astro-sdk#615] opened 2022-08-08 08:16 UTC
**Describe the bug**
@manmeetkaur reported this issue. She described the following: 
I have a deployment where I want to use `dbt-snowflake` and `astro-sdk-python`  . When I add them individually to requirements.txt  file it works but if I add them both, astro dev start fails. It prints a fairly long error message. 

```
+ grep -Eqx 'apache-airflow\s*[=~>]{1,2}.*' requirements.txt
+ pip install --no-cache-dir -q -r requirements.txt
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /tmp/pip-standalone-pip-8mzs5p86/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ubix46n6/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://pip.astronomer.io/simple/astronomer-fab-security-manager/ -- 'setuptools>=40.6.0' wheel cython 'pyarrow>=0.17.0,<0.18.0'
       cwd: None
  Complete output (1202 lines):
  Looking in links: https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/
  Collecting setuptools>=40.6.0
    Downloading setuptools-63.4.1-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting cython
    Downloading Cython-0.29.32-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
  Collecting pyarrow<0.18.0,>=0.17.0
    Downloading pyarrow-0.17.1.tar.gz (2.6 MB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /tmp/pip-standalone-pip-8mzs5p86/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-twd_r1t3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links https://pip.astronomer.io/simple/astronomer-fab-security-manager/ --find-links https://pip.astronomer.io/simple/astronomer-fab-security-manager/ -- 'cython >= 0.29' 'numpy==1.14.5; python_version<'"'"'3.7'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"'' setuptools setuptools_scm wheel
         cwd: None
    Complete output (585 lines):
    Looking in links: https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/
    Ignoring numpy: markers 'python_version < "3.7"' don't match your environment
    Collecting cython>=0.29
      Downloading Cython-0.29.32-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
    Collecting numpy==1.16.0
      Downloading numpy-1.16.0.zip (5.1 MB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting setuptools
      Downloading setuptools-63.4.1-py3-none-any.whl (1.2 MB)
    Collecting setuptools_scm
      Downloading setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
    Collecting wheel
      Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
    Collecting typing-extensions
      Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
    Collecting packaging>=20.0
      Downloading packaging-21.3-py3-none-any.whl (40 kB)
    Collecting tomli>=1.0.0
      Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
    Collecting pyparsing!=3.0.5,>=2.0.2
      Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
    Building wheels for collected packages: numpy
      Building wheel for numpy (setup.py): started
      Building wheel for numpy (setup.py): finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hjixk2k1
           cwd: /tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/
      Complete output (259 lines):
      Running from numpy source directory.
      /tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/numpy/distutils/misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
        return is_string(s) and ('*' in s or '?' is s)
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      blis_info:
      customize UnixCCompiler
        libraries blis not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      openblas_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      customize UnixCCompiler
        libraries satlas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_info:
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      /tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/numpy/distutils/system_info.py:625: UserWarning:
          Atlas (http://math-atlas.sourceforge.net/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [atlas]) or by setting
          the ATLAS environment variable.
        self.calc_info()
      blas_info:
      customize UnixCCompiler
        libraries blas not found in ['/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      /tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/numpy/distutils/system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE

      /tmp/pip-install-fbaogk5g/numpy_f7a9d66a37b249d98a9a795f46f7de54/numpy/distutils/system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
```

**Version**
* astro-sdk-python: latest
* OS: mac M1 max and mac M1 pro

**To Reproduce**
1. Use the following dockerfile
```
FROM quay.io/astronomer/astro-runtime:5.0.6

ENV AIRFLOW__SECRETS__BACKEND="airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend"
ENV AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables"}'

ENV AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
ENV AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
ENV AIRFLOW__LINEAGE__BACKEND=
ENV OPENLINEAGE_DISABLED=True

```
2. requirements.txt
```
astro-sdk-python
dbt-snowflake
```
3. Run `astro dev init` and `astro dev start`

**Expected behavior**
Both library should run fine together with astro cli

**Comment by sunank200** [comment] 2022-08-08 08:30
After debugging following are the observations:
- Only `astro-sdk-python` on requirements.txt works fine with astro dev start
- Only `dbt-snowflake` works fine with astro dev start
- Both `astro-sdk-python` and `dbt-snowflake` install fine on virtualenv or conda environment. This issue did not replicate in virtual environment.

**Conclusion**
If we install in conda environment or virtual environment `astro-sdk-python` and `dbt-snowflake` installs `pandas=1.3.5`. But in astro runtime, it conflicts and fails to build numpy. I tried explicitly adding `--platform linux/amd64` in ` the astro command as well but it doesn't work. `astro dev start` as per this [dockerfile](https://github.com/astronomer/astro-runtime/blob/5-1-0-dev/image/Dockerfile) in astro runtime install various libraries including astronomer-providers and airflow providers. I tired the same in the virtual environment (in the same order) and it works fine. My understanding is that there is something internal(which we are not aware of) with astro runtime which is causing this conflict because it works fine in python virtual environments.

cc: @kaxil , @tatiana @manmeetkaur @dimberman @utkarsharma2

**Comment by sunank200** [comment] 2022-08-08 09:27
@kaxil please take a look whenever you have time.

**Comment by kaxil** [comment] 2022-08-08 09:27
I will take a look at it tomorrow

**Comment by kaxil** [comment] 2022-08-09 21:00
Looks like you can easily reproduce the issue by running the following on an M1 Mac:

```
docker run -it quay.io/astronomer/astro-runtime:5.0.6 /bin/bash
pip install 'numpy==1.16.0'
```

This happens when installing an older version of numpy which didn't have artifacts for M1:

```
              ERROR: Failed cleaning build dir for numpy
            Failed to build numpy
            Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyparsing, numpy, cython, packaging, setuptools_scm
              Running setup.py install for numpy: started
              Running setup.py install for numpy: finished with status 'error'
              error: subprocess-exited-with-error

              × Running setup.py install for numpy did not run successfully.
              │ exit code: 1
              ╰─> [267 lines of output]
                  Running from numpy source directory.
```


----


The main issue is the following where the main version of Jinja2 conflicts in [`dbt-core`](https://github.com/dbt-labs/dbt-core/blob/v1.2.0/core/setup.py#L51) (which needs `"Jinja2==2.11.3"`) and [`flask`](https://github.com/pallets/flask/blob/2.1.2/setup.py#L8) (which needs `Jinja2>3`) that is needed by Airflow:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.1.2 requires Jinja2>=3.0, but you have jinja2 2.11.3 which is incompatible.
Successfully installed Jinja2-2.11.3 SecretStorage-3.3.2 agate-1.6.3 dbt-core-1.2.0 dbt-extractor-0.4.1 dbt-snowflake-1.2.0 hologram-0.0.15 jeepney-0.8.0 jsonschema-3.2.0 keyring-23.8.2 leather-0.3.4 logbook-1.5.3 mashumaro-2.9 minimal-snowplow-tracker-0.0.2 msgpack-1.0.4 networkx-2.8.5 parsedatetime-2.4 pytimeparse-1.1.8
```

The following works fine because the new version of [`dbt-core`](https://github.com/dbt-labs/dbt-core/blob/v1.3.0b1/core/setup.py#L51) needs `"Jinja2==3.1.2"`. This was fixed in https://github.com/dbt-labs/dbt-core/pull/5465 , so installing a dev version for dbt-snowflake as below works fine:
```
pip install astro-sdk-python 'dbt-snowflake==1.3.0b1'
```

**Closed by kaxil** 2022-08-09 21:00 UTC
Labels: bug
